apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-alfresco-volume
  # The label is used for matching the exact claim
  labels:
    usage: pv-alfresco-volume
spec:
  capacity:
    storage: {{ .Values.azurepvc.infra.baseSize | quote }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy | default "Recycle" }}
  azureFile:
    secretName: {{ .Values.azurepvc.infra.secretName }}
    shareName:  {{ .Values.azurepvc.infra.shareName }}
    # In case the secret is stored in a different namespace
    shareNamespace: {{ .Values.persistence.shareNamespace | default "default" }}
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alfresco-volume-claim
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.azurepvc.infra.baseSize | quote }}
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: pv-alfresco-volume

