# Default values for alfresco-search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Define the alfresco-search properties to use in the k8s cluster
# This is the search provider used by alfresco-content-repository
replicaCount: 1
# Define the type of Alfresco Search to use. The default is Alfresco Search Services.
# The type can be set to use Insight Engine with --set alfresco-search.type="insight-engine",alfresco-search.registryPullSecrets="quay-registry-secret",alfresco-insight-zeppelin.enabled="true"
# As the Docker Image for Insight Engine is not publicly available the registryPullSecrets has to be set
# More information can be found on https://github.com/Alfresco/alfresco-anaxes-shipyard/blob/master/SECRETS.md
type: "search-services"
searchServicesImage:
  repository: alfresco/alfresco-search-services
  tag: "1.3.0-RC2"
  pullPolicy: &searchDockerImagePullPolicy Always
  internalPort: &searchDockerImageInternalPort 8983
insightEngineImage:
  repository: quay.io/alfresco/insight-engine
  tag: "1.0.0"
  pullPolicy: *searchDockerImagePullPolicy
  internalPort: *searchDockerImageInternalPort
service:
  name: solr
  type: ClusterIP
  externalPort: 80
ingress:
  enabled: false
  path: /solr
  # Default solr basic auth user/password: admin / admin
  # You can create your own with htpasswd utilility & encode it with base640.
  # Example: `echo -n "$(htpasswd -nbm admin admin)" | base64` # i.e. admin / admin
  # basicAuth: YWRtaW46JGFwcjEkVVJqb29uS00kSEMuS1EwVkRScFpwSHB2a3JwTDd1Lg==
  basicAuth: YWRtaW46JGFwcjEkVVJqb29uS00kSEMuS1EwVkRScFpwSHB2a3JwTDd1Lg==
  # Comma separated list of IP CIDR to limit search endpoint over the internet
  whitelist_ips: "0.0.0.0/0"
# The parent chart will set the values for "repository.host" and "repository.port"
repository: {}
environment:
  SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
#  SOLR_OPTS: "-Dsolr.content.dir=/opt/alfresco-search-services/data/contentstore"
resources:
  requests:
    memory: "250Mi"
  limits:
    memory: "1024Mi"
# Defines the mounting points for the persistence required by the apps in the cluster
# the solr data folder containing the indexes for the alfresco-search-services is mapped to alfresco-content-services/solr-data
persistence:
  # existingClaim: "search-master-claim" #Only define if you have a specific claim already created
  VolumeSizeRequest: 10Gi
  storageClassName: "managed-premium"
  search:
    data:
      mountPath: "/opt/alfresco-search-services/data"
      subPath: "alfresco-content-services/solr-data"
  EbsPvConfiguration:
    fsType: ext4
alfresco-insight-zeppelin:
  enabled: false

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: "component"
          operator: In
          values:
          - "search"
      topologyKey: kubernetes.io/hostname